version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
  - cmd: dotnet restore

build:
  - verbosity: minimal

test_script:
  - cmd: dotnet test src/Insql.Tests.csproj

after_build:
  - cmd: dotnet pack src/Insql.csproj --configuration Release

artifacts:
  - path: '**/*.nupkg'